### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by oleg-shilo** [laszlojakab/hikvision-intercom-python-demo#5]
Thank you so much for such an excellent sample.

Any chance you have a Linux version?
I see the Linux `LoadLibrary` version but after making `HCNetSDK.NET_DVR_Login_V30` call it crashes in case of the successful login with the error:
```
Bus error (core dumped)
```

Any hint or suggestion?

**Comment by pergolafabio** [comment]
Have a look here...
https://github.com/laszlojakab/hikvision-intercom-python-demo/issues/2

**Comment by oleg-shilo** [comment]
If only everything was as easy in life :)
Thank you for pointing me in the right direction. Removing `device_info` did the trick.

**Comment by pergolafabio** [comment]
Perfect. :-)
