### ISSUE TITLE
"cannot open shared object file: No such file or directory" error is coming while cdll.LoadLibrary()

### ISSUE THREAD

**Issue by Vignesh-AK** [laszlojakab/hikvision-intercom-python-demo#7]
"cannot open shared object file: No such file or directory" error is coming while cdll.LoadLibrary()

File "/home/cf/hikvision-intercom-python-demo/hcnetsdk.py", line 162, in <module>
    HCNetSDK = cdll.LoadLibrary(hcnetsdk_path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/cf/hikvision-intercom-python-demo/EN-HCNetSDKV6.1.9.4_build20220412_linux64/lib/libhcnetsdk.so: cannot open shared object file: No such file or directory

**Comment by pergolafabio** [comment]
check if your path is correct, or maybe permission error?

**Comment by pergolafabio** [comment]
are you using Home Assistant btw?

**Comment by Vignesh-AK** [comment]
I am not using Home assistant. Just running this in rasperrypi (debian). The path is correct. I have validated it with linux command

**Comment by pergolafabio** [comment]
the sdk is not supported for Aarch64 , only x64

**Comment by pergolafabio** [comment]
try this folder, i got sdk from hikvision, but never tested , since i dont have an RPI
take this folder:

https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-sdk/lib-arm_aarch64-linux

**Comment by Vignesh-AK** [comment]
Is there any way we can install SDK ?

**Comment by pergolafabio** [comment]
take my folder, in reply above, its an SDK for RPI (aarch64) but i have never tested it
keep me posted

**Comment by Vignesh-AK** [comment]
Thanks

**Comment by Vignesh-AK** [comment]
That's working !

**Comment by pergolafabio** [comment]
Aha, cool, you are the first confirming that it works on RPI :-)

**Comment by Vignesh-AK** [comment]
Yeah its working bro

**Comment by pergolafabio** [comment]
yeah, but how did you fix error 29 ? what was the issue?

**Comment by cerahmed** [comment]
> try this folder, i got sdk from hikvision, but never tested , since i dont have an RPI take this folder:
> 
> https://github.com/pergolafabio/Hikvision-Addons/tree/main/hikvision-sdk/lib-arm_aarch64-linux

I'm running into the same problem while running the code in RPI. @pergolafabio @Vignesh-AK, the link for the aarch64 is no longer working, do you still have a copy of the files you can share?

**Comment by pergolafabio** [comment]
Sure, look here for addon:

https://github.com/pergolafabio/Hikvision-Addons/tree/main

source and project can be found here:

https://github.com/pergolafabio/Hikvision-Addons/tree/dev/hikvision-doorbell

**Comment by cerahmed** [comment]
Thanks a bunch @pergolafabio! It's now working great on the pi.
My sole purpose of using this script it to detect when the `unlock` button is pressed from my indoor station, then run a custom script.

Thanks again for this useful script!

**Comment by pergolafabio** [comment]
if you want , you can use my project, it can also run as standalone container, also on dockerhub
it can capture a lot more events!

**Comment by cerahmed** [comment]
> if you want , you can use my project, it can also run as standalone container, also on dockerhub it can capture a lot more events!

I am indeed using your project in conjuction with the `aarch64` Hikvision SDK to achieve this.

**Comment by pergolafabio** [comment]
Perfect:-)
