### ISSUE TITLE
I am getting NET_DVR_Login_V30 failed, error code = 29 while importing requests library 

### ISSUE THREAD

**Issue by Vignesh-AK** [laszlojakab/hikvision-intercom-python-demo#8]
error code  -  NET_DVR_Login_V30 failed, error code = 29

login - device_info = NET_DVR_DEVICEINFO_V30()

                                  user_id = HCNetSDK.NET_DVR_Login_V30( "192.168.2.3".encode('utf-8'), 8000, "admin".encode('utf-8'), "Futurehook7".encode('utf-8'), device_info)
                                  
                                  if (user_id < 0):
                                      print(
                                          f"NET_DVR_Login_V30 failed, error code = {HCNetSDK.NET_DVR_GetLastError()}")
                                      HCNetSDK.NET_DVR_Cleanup()
                                      exit(1)

import - from base64 import b64encode
from hcnetsdk import HCNetSDK, NET_DVR_DEVICEINFO_V30, NET_DVR_DEVICEINFO_V30, NET_DVR_SETUPALARM_PARAM, fMessageCallBack, COMM_ALARM_V30, COMM_ALARM_VIDEO_INTERCOM, NET_DVR_VIDEO_INTERCOM_ALARM, NET_DVR_ALARMINFO_V30, ALARMINFO_V30_ALARMTYPE_MOTION_DETECTION, VIDEO_INTERCOM_ALARM_ALARMTYPE_DOORBELL_RINGING, VIDEO_INTERCOM_ALARM_ALARMTYPE_DISMISS_INCOMING_CALL, VIDEO_INTERCOM_ALARM_ALARMTYPE_TAMPERING_ALARM, VIDEO_INTERCOM_ALARM_ALARMTYPE_DOOR_NOT_CLOSED, COMM_UPLOAD_VIDEO_INTERCOM_EVENT, NET_DVR_VIDEO_INTERCOM_EVENT, VIDEO_INTERCOM_EVENT_EVENTTYPE_UNLOCK_LOG, VIDEO_INTERCOM_EVENT_EVENTTYPE_ILLEGAL_CARD_SWIPING_EVENT, NET_DVR_UNLOCK_RECORD_INFO
from ctypes import POINTER, cast, c_char_p, c_byte
import requests as req

**Comment by pergolafabio** [comment]
Yeah hzd that error too before I think you are running an unsupported OS, the new SDK is maybe working for aarch64, but it's also picky about the OS... 

I was testig before on Alpine OS, received error 29, and then switched over to pure Debian...

I'll ask hikvision what OS is supported for this aarch64 SDK

**Comment by pergolafabio** [comment]
Got feedback, seems the SDK was only tested against those OS : Phytium ,Huawei...

They have no plans in future to make support for other OS... Maybe run it in docker container, I did it too for my addon...

Or just try another OS

**Comment by pergolafabio** [comment]
I think they mean EulerOs , for Huawei, there is a docker for it

**Comment by pergolafabio** [comment]
@laszlojakab , this is also verry usefull for you too ; not sure if you already tested the SDK for RPI aarch64 ?

**Comment by Vignesh-AK** [comment]
I fixed that issue , thank you guys

**Comment by pergolafabio** [comment]
how did yo fix? interested in this one, i also want to make support for HA and RPI users
