### ISSUE TITLE
Two-way audio in Video Door Phone

### ISSUE THREAD

**Issue by Vignesh-AK** [laszlojakab/hikvision-intercom-python-demo#9]
Can we enable and live stream Two-Way audio using Hik Vision SDK. I am using FRPS to stream the live video

**Comment by pergolafabio** [comment]
Yes, probably, but two way audio is not part of the script, but its in the SDK documentation
you can also use ISAPI for it too if you want

**Comment by Vignesh-AK** [comment]
Could you please share me the SDK Documentation. I couldn't find that

**Comment by pergolafabio** [comment]
first hit google :-)

https://www.hikvision.com/en/support/download/sdk/
